# Generated by Django 5.1 on 2024-08-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False)),
                ('pay', models.IntegerField(blank=True, null=True)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Offer', 'Offer'), ('Rejected', 'Rejected'), ('Interviewing', 'Interviewing'), ('Waiting', 'Waiting')], default='Waiting', max_length=12)),
                ('notes', models.TextField()),
            ],
        ),
    ]
