# Generated by Django 5.1 on 2024-09-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='refferal',
            new_name='referral',
        ),
        migrations.AlterField(
            model_name='connection',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
